import React, { useState, useEffect, useCallback } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  SafeAreaView,
  ActivityIndicator,
  Switch,
  Alert,
} from 'react-native';
import { useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { Colors } from '@/constants/theme';
import { useAuth } from '@/hooks/useAuth';
import { useProfile } from '@/hooks/useProfile';
import { profileService } from '@/services/profile';
import { SocialProfileResponse, ProfileVisibilityUpdate } from '@/types/profile';
import { useOnboarding } from '@/hooks/useOnboarding';

export default function ProfileScreen() {
  const router = useRouter();
  const { user, logout } = useAuth();
  const { data: onboardingData } = useOnboarding();
  const {
    profile,
    visibility,
    isLoading: profileLoading,
    error: profileError,
    refreshProfile,
    updateVisibility,
  } = useProfile();

  const [socialPreview, setSocialPreview] = useState<SocialProfileResponse | null>(null);
  const [isLoadingPreview, setIsLoadingPreview] = useState(false);
  const [isLoggingOut, setIsLoggingOut] = useState(false);

  // Load the live social preview generated by the backend for this user
  const fetchSocialPreview = useCallback(async () => {
    if (!user?.id) return;
    try {
      setIsLoadingPreview(true);
      const preview = await profileService.getUserProfile(user.id);
      setSocialPreview(preview);
    } catch {
      // Social preview non-critical
    } finally {
      setIsLoadingPreview(false);
    }
  }, [user?.id]);

  useEffect(() => {
    fetchSocialPreview();
  }, [fetchSocialPreview, visibility]);

  const handleToggleVisibility = async (key: keyof ProfileVisibilityUpdate, currentValue: boolean) => {
    const newValue = !currentValue;
    try {
      await updateVisibility({ [key]: newValue });
      await fetchSocialPreview();
    } catch (err: any) {
      Alert.alert('Privacy Update Notice', err.message || 'Could not update visibility setting.');
    }
  };

  const handleLogoutPress = () => {
    Alert.alert(
      'Log out of FocusLoop?',
      "You'll need to sign in again to access your account.",
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Log Out',
          style: 'destructive',
          onPress: async () => {
            try {
              setIsLoggingOut(true);
              await logout();
              router.replace('/login');
            } catch (err: any) {
              Alert.alert('Logout Notice', err.message || 'Could not complete logout.');
            } finally {
              setIsLoggingOut(false);
            }
          },
        },
      ]
    );
  };

  return (
    <SafeAreaView style={styles.safeArea}>
      {/* Top Custom App Navigation Header */}
      <View style={styles.topHeader}>
        <TouchableOpacity
          style={styles.backButton}
          onPress={() => router.back()}
          activeOpacity={0.7}
        >
          <Ionicons name="arrow-back" size={22} color={Colors.textStrong} />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>My Profile</Text>
        <View style={{ width: 40 }} />
      </View>

      <ScrollView
        style={styles.container}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
      >
        {profileLoading ? (
          <View style={styles.loadingBox}>
            <ActivityIndicator size="large" color={Colors.primary} />
            <Text style={styles.loadingText}>Loading profile snapshot...</Text>
          </View>
        ) : profileError ? (
          <View style={styles.errorBox}>
            <Ionicons name="alert-circle-outline" size={28} color="#DC2626" />
            <Text style={styles.errorTitle}>Could not load profile</Text>
            <Text style={styles.errorDesc}>{profileError}</Text>
            <TouchableOpacity style={styles.retryBtn} onPress={refreshProfile}>
              <Text style={styles.retryBtnText}>Retry</Text>
            </TouchableOpacity>
          </View>
        ) : (
          <>
            {/* ── 1. Identity Card ── */}
            <View style={styles.identityCard}>
              <View style={styles.avatarLarge}>
                <Text style={styles.avatarInitial}>
                  {(user?.name || profile?.identity?.name || 'Explorer').charAt(0).toUpperCase()}
                </Text>
              </View>
              <View style={styles.identityTextColumn}>
                <Text style={styles.profileName}>
                  {user?.name || profile?.identity?.name || 'FocusLoop Explorer'}
                </Text>
                <Text style={styles.profileHandle}>
                  {user?.username ? `@${user.username}` : user?.email || 'FocusLoop Member'}
                </Text>
                {user?.email && user.username ? (
                  <Text style={styles.profileEmail}>{user.email}</Text>
                ) : null}
              </View>
            </View>

            {/* ── 2. Personal Progress Snapshot (Owner View) ── */}
            <View style={styles.sectionCard}>
              <View style={styles.cardHeaderRow}>
                <View style={styles.cardIconBox}>
                  <Ionicons name="analytics" size={16} color={Colors.primary} />
                </View>
                <Text style={styles.cardTitle}>Personal Progress Snapshot</Text>
                <View style={styles.privateOwnerTag}>
                  <Ionicons name="lock-closed" size={10} color={Colors.secondary} />
                  <Text style={styles.privateOwnerText}>Owner View</Text>
                </View>
              </View>

              <Text style={styles.sectionSubtitle}>
                Verified behavioral scores and level progress calculated by the FocusLoop engine.
              </Text>

              {/* Private Metrics Row */}
              <View style={styles.metricsGrid}>
                {/* Current Level */}
                <View style={[styles.metricTile, { backgroundColor: Colors.surfaceTintViolet }]}>
                  <View style={styles.metricTileHeader}>
                    <Text style={[styles.metricLabel, { color: Colors.primary }]}>CURRENT LEVEL</Text>
                    <View style={styles.privacyMiniBadge}>
                      <Ionicons
                        name={visibility?.current_level ? 'globe-outline' : 'lock-closed'}
                        size={10}
                        color={visibility?.current_level ? Colors.secondary : Colors.textMuted}
                      />
                      <Text style={styles.privacyMiniText}>
                        {visibility?.current_level ? 'Public' : 'Private'}
                      </Text>
                    </View>
                  </View>
                  <Text style={styles.metricValueLarge}>
                    {profile?.metrics?.current_level || '1 — Foundation'}
                  </Text>
                  <Text style={styles.metricSub}>
                    {profile?.metrics?.level_info?.title || 'Behavioral Foundation'}
                  </Text>
                </View>

                {/* Behavior Score */}
                <View style={[styles.metricTile, { backgroundColor: Colors.surfaceTintBlue }]}>
                  <View style={styles.metricTileHeader}>
                    <Text style={[styles.metricLabel, { color: Colors.accentIndigo }]}>BEHAVIOR SCORE</Text>
                    <View style={styles.privacyMiniBadge}>
                      <Ionicons
                        name={visibility?.behavior_score ? 'globe-outline' : 'lock-closed'}
                        size={10}
                        color={visibility?.behavior_score ? Colors.secondary : Colors.textMuted}
                      />
                      <Text style={styles.privacyMiniText}>
                        {visibility?.behavior_score ? 'Public' : 'Private'}
                      </Text>
                    </View>
                  </View>
                  <Text style={styles.metricValueLarge}>
                    {profile?.metrics?.behavior_score != null
                      ? profile.metrics.behavior_score.toFixed(0)
                      : '—'}
                  </Text>
                  <Text style={styles.metricSub}>Private diagnostic score</Text>
                </View>
              </View>

              {/* Public-by-default metrics strip */}
              <View style={styles.publicMetricsStrip}>
                <View style={styles.publicMetricCol}>
                  <Text style={styles.publicMetricVal}>
                    {profile?.metrics?.improvement_score != null
                      ? profile.metrics.improvement_score.toFixed(1)
                      : '—'}
                  </Text>
                  <Text style={styles.publicMetricLabel}>Improvement</Text>
                </View>
                <View style={styles.metricDivider} />
                <View style={styles.publicMetricCol}>
                  <Text style={styles.publicMetricVal}>
                    {profile?.metrics?.consistency != null
                      ? `${Math.round(profile.metrics.consistency)}%`
                      : '—'}
                  </Text>
                  <Text style={styles.publicMetricLabel}>Consistency</Text>
                </View>
                <View style={styles.metricDivider} />
                <View style={styles.publicMetricCol}>
                  <Text style={styles.publicMetricVal}>
                    {profile?.metrics?.experiment_effectiveness != null
                      ? `${Math.round(profile.metrics.experiment_effectiveness)}%`
                      : '—'}
                  </Text>
                  <Text style={styles.publicMetricLabel}>Effectiveness</Text>
                </View>
              </View>
            </View>

            {/* ── 2B. Focus Goal & Context (Owner View) ── */}
            <View style={styles.sectionCard}>
              <View style={styles.cardHeaderRow}>
                <View style={[styles.cardIconBox, { backgroundColor: Colors.surfaceTintViolet }]}>
                  <Ionicons name="flag-outline" size={16} color={Colors.primary} />
                </View>
                <Text style={styles.cardTitle}>Focus Goal & Context</Text>
                <View style={styles.privateOwnerTag}>
                  <Ionicons name="lock-closed" size={10} color={Colors.secondary} />
                  <Text style={styles.privateOwnerText}>Owner Only</Text>
                </View>
              </View>

              <Text style={styles.sectionSubtitle}>
                Your self-reported focus goals, schedule availability, and focus roadblocks.
              </Text>

              <View style={styles.contextSummaryBox}>
                <View style={styles.contextSummaryRow}>
                  <Text style={styles.contextLabel}>PRIMARY GOAL</Text>
                  <Text style={styles.contextValue}>
                    {onboardingData?.goal?.category || 'General Focus'}
                    {onboardingData?.goal?.description ? ` — ${onboardingData.goal.description}` : ''}
                  </Text>
                </View>

                <View style={styles.contextSummaryRow}>
                  <Text style={styles.contextLabel}>PREFERRED WINDOW & AVAILABILITY</Text>
                  <Text style={styles.contextValue}>
                    {onboardingData?.routine?.preferred_time_window || 'Flexible'} • {onboardingData?.routine?.daily_available_duration || '1–2 hours'}
                  </Text>
                </View>

                {onboardingData?.challenges && onboardingData.challenges.length > 0 && (
                  <View style={styles.contextSummaryRow}>
                    <Text style={styles.contextLabel}>FOCUS ROADBLOCKS</Text>
                    <Text style={styles.contextValue}>
                      {onboardingData.challenges.map((c) => c.challenge_text).join(', ')}
                    </Text>
                  </View>
                )}

                {onboardingData?.interests && onboardingData.interests.length > 0 && (
                  <View style={styles.contextSummaryRow}>
                    <Text style={styles.contextLabel}>INTERESTS & PASSIONS</Text>
                    <Text style={styles.contextValue}>
                      {onboardingData.interests.map((i) => i.interest_text).join(', ')}
                    </Text>
                  </View>
                )}
              </View>

              <TouchableOpacity
                style={styles.editContextBtn}
                onPress={() => router.push('/onboarding' as any)}
                activeOpacity={0.8}
              >
                <Ionicons name="create-outline" size={16} color={Colors.primary} />
                <Text style={styles.editContextBtnText}>Update Goal & Starting Context</Text>
              </TouchableOpacity>
            </View>

            {/* ── 3. Privacy & Sharing Controls ── */}
            <View style={styles.sectionCard}>
              <View style={styles.cardHeaderRow}>
                <View style={[styles.cardIconBox, { backgroundColor: Colors.surfaceTintMint }]}>
                  <Ionicons name="shield-checkmark" size={16} color={Colors.secondary} />
                </View>
                <Text style={styles.cardTitle}>Privacy & Sharing</Text>
              </View>

              <Text style={styles.sectionSubtitle}>
                Control which metrics friends and social circles can see. Sensitive internal intelligence is never shared.
              </Text>

              {visibility && (
                <View style={styles.togglesList}>
                  {/* Current Level Toggle */}
                  <View style={styles.toggleRow}>
                    <View style={styles.toggleInfo}>
                      <View style={styles.toggleTitleRow}>
                        <Text style={styles.toggleTitle}>Current Level</Text>
                        <View
                          style={[
                            styles.badgePill,
                            visibility.current_level ? styles.badgePublic : styles.badgePrivate,
                          ]}
                        >
                          <Text
                            style={[
                              styles.badgeText,
                              visibility.current_level ? styles.badgeTextPublic : styles.badgeTextPrivate,
                            ]}
                          >
                            {visibility.current_level ? 'Public' : 'Private'}
                          </Text>
                        </View>
                      </View>
                      <Text style={styles.toggleDesc}>
                        Share your focus level milestone with connections.
                      </Text>
                    </View>
                    <Switch
                      value={visibility.current_level}
                      onValueChange={() =>
                        handleToggleVisibility('current_level', visibility.current_level)
                      }
                      trackColor={{ false: '#D1D5DB', true: Colors.primary }}
                      thumbColor="#FFFFFF"
                    />
                  </View>

                  {/* Behavior Score Toggle */}
                  <View style={styles.toggleRow}>
                    <View style={styles.toggleInfo}>
                      <View style={styles.toggleTitleRow}>
                        <Text style={styles.toggleTitle}>Behavior Score</Text>
                        <View
                          style={[
                            styles.badgePill,
                            visibility.behavior_score ? styles.badgePublic : styles.badgePrivate,
                          ]}
                        >
                          <Text
                            style={[
                              styles.badgeText,
                              visibility.behavior_score ? styles.badgeTextPublic : styles.badgeTextPrivate,
                            ]}
                          >
                            {visibility.behavior_score ? 'Public' : 'Private'}
                          </Text>
                        </View>
                      </View>
                      <Text style={styles.toggleDesc}>
                        Your private behavioral index. Hidden from friends by default.
                      </Text>
                    </View>
                    <Switch
                      value={visibility.behavior_score}
                      onValueChange={() =>
                        handleToggleVisibility('behavior_score', visibility.behavior_score)
                      }
                      trackColor={{ false: '#D1D5DB', true: Colors.primary }}
                      thumbColor="#FFFFFF"
                    />
                  </View>

                  {/* Improvement Score Toggle */}
                  <View style={styles.toggleRow}>
                    <View style={styles.toggleInfo}>
                      <View style={styles.toggleTitleRow}>
                        <Text style={styles.toggleTitle}>Improvement Score</Text>
                        <View
                          style={[
                            styles.badgePill,
                            visibility.improvement_score ? styles.badgePublic : styles.badgePrivate,
                          ]}
                        >
                          <Text
                            style={[
                              styles.badgeText,
                              visibility.improvement_score ? styles.badgeTextPublic : styles.badgeTextPrivate,
                            ]}
                          >
                            {visibility.improvement_score ? 'Public' : 'Private'}
                          </Text>
                        </View>
                      </View>
                      <Text style={styles.toggleDesc}>
                        Shows your growth rate across completed tasks.
                      </Text>
                    </View>
                    <Switch
                      value={visibility.improvement_score}
                      onValueChange={() =>
                        handleToggleVisibility('improvement_score', visibility.improvement_score)
                      }
                      trackColor={{ false: '#D1D5DB', true: Colors.primary }}
                      thumbColor="#FFFFFF"
                    />
                  </View>

                  {/* Experiment Effectiveness Toggle */}
                  <View style={styles.toggleRow}>
                    <View style={styles.toggleInfo}>
                      <View style={styles.toggleTitleRow}>
                        <Text style={styles.toggleTitle}>Experiment Effectiveness</Text>
                        <View
                          style={[
                            styles.badgePill,
                            visibility.experiment_effectiveness ? styles.badgePublic : styles.badgePrivate,
                          ]}
                        >
                          <Text
                            style={[
                              styles.badgeText,
                              visibility.experiment_effectiveness ? styles.badgeTextPublic : styles.badgeTextPrivate,
                            ]}
                          >
                            {visibility.experiment_effectiveness ? 'Public' : 'Private'}
                          </Text>
                        </View>
                      </View>
                      <Text style={styles.toggleDesc}>
                        Shows empirical protocol outcome ratings.
                      </Text>
                    </View>
                    <Switch
                      value={visibility.experiment_effectiveness}
                      onValueChange={() =>
                        handleToggleVisibility('experiment_effectiveness', visibility.experiment_effectiveness)
                      }
                      trackColor={{ false: '#D1D5DB', true: Colors.primary }}
                      thumbColor="#FFFFFF"
                    />
                  </View>

                  {/* Consistency Toggle */}
                  <View style={styles.toggleRow}>
                    <View style={styles.toggleInfo}>
                      <View style={styles.toggleTitleRow}>
                        <Text style={styles.toggleTitle}>Consistency Rating</Text>
                        <View
                          style={[
                            styles.badgePill,
                            visibility.consistency ? styles.badgePublic : styles.badgePrivate,
                          ]}
                        >
                          <Text
                            style={[
                              styles.badgeText,
                              visibility.consistency ? styles.badgeTextPublic : styles.badgeTextPrivate,
                            ]}
                          >
                            {visibility.consistency ? 'Public' : 'Private'}
                          </Text>
                        </View>
                      </View>
                      <Text style={styles.toggleDesc}>
                        Shows how reliably you check in over time.
                      </Text>
                    </View>
                    <Switch
                      value={visibility.consistency}
                      onValueChange={() =>
                        handleToggleVisibility('consistency', visibility.consistency)
                      }
                      trackColor={{ false: '#D1D5DB', true: Colors.primary }}
                      thumbColor="#FFFFFF"
                    />
                  </View>

                  {/* Behavioral Patterns Toggle */}
                  <View style={styles.toggleRow}>
                    <View style={styles.toggleInfo}>
                      <View style={styles.toggleTitleRow}>
                        <Text style={styles.toggleTitle}>Behavioral Patterns</Text>
                        <View
                          style={[
                            styles.badgePill,
                            visibility.behavioral_patterns ? styles.badgePublic : styles.badgePrivate,
                          ]}
                        >
                          <Text
                            style={[
                              styles.badgeText,
                              visibility.behavioral_patterns ? styles.badgeTextPublic : styles.badgeTextPrivate,
                            ]}
                          >
                            {visibility.behavioral_patterns ? 'Public' : 'Private'}
                          </Text>
                        </View>
                      </View>
                      <Text style={styles.toggleDesc}>
                        Share high-level focus and hesitation patterns with friends.
                      </Text>
                    </View>
                    <Switch
                      value={visibility.behavioral_patterns}
                      onValueChange={() =>
                        handleToggleVisibility('behavioral_patterns', visibility.behavioral_patterns)
                      }
                      trackColor={{ false: '#D1D5DB', true: Colors.primary }}
                      thumbColor="#FFFFFF"
                    />
                  </View>
                </View>
              )}
            </View>

            {/* ── 4. Public Profile Preview ("How Others See You") ── */}
            <View style={styles.sectionCard}>
              <View style={styles.cardHeaderRow}>
                <View style={[styles.cardIconBox, { backgroundColor: Colors.surfaceTintAmber }]}>
                  <Ionicons name="eye-outline" size={16} color={Colors.tertiary} />
                </View>
                <Text style={styles.cardTitle}>How Others See You</Text>
                <View style={styles.publicTag}>
                  <Ionicons name="globe-outline" size={10} color={Colors.primary} />
                  <Text style={styles.publicTagText}>Live Preview</Text>
                </View>
              </View>

              <Text style={styles.sectionSubtitle}>
                This is the exact public card shown to your connected friends, sanitized by your privacy settings above.
              </Text>

              {isLoadingPreview ? (
                <View style={{ padding: 16, alignItems: 'center' }}>
                  <ActivityIndicator size="small" color={Colors.primary} />
                </View>
              ) : socialPreview ? (
                <View style={styles.previewContainer}>
                  <View style={styles.previewHeader}>
                    <View style={styles.previewAvatar}>
                      <Text style={styles.previewAvatarText}>
                        {socialPreview.identity.name.charAt(0).toUpperCase()}
                      </Text>
                    </View>
                    <View style={{ flex: 1 }}>
                      <Text style={styles.previewName}>{socialPreview.identity.name}</Text>
                      <Text style={styles.previewSub}>
                        {socialPreview.identity.username
                          ? `@${socialPreview.identity.username}`
                          : 'Public Profile'}
                      </Text>
                    </View>
                  </View>

                  {/* Public Metrics Display */}
                  <View style={styles.previewMetricsGrid}>
                    <View style={styles.previewMetricItem}>
                      <Text style={styles.previewMetricVal}>
                        {socialPreview.metrics.improvement_score != null
                          ? socialPreview.metrics.improvement_score.toFixed(1)
                          : '—'}
                      </Text>
                      <Text style={styles.previewMetricLabel}>Improvement</Text>
                    </View>
                    <View style={styles.previewMetricItem}>
                      <Text style={styles.previewMetricVal}>
                        {socialPreview.metrics.consistency != null
                          ? `${Math.round(socialPreview.metrics.consistency)}%`
                          : '—'}
                      </Text>
                      <Text style={styles.previewMetricLabel}>Consistency</Text>
                    </View>
                    <View style={styles.previewMetricItem}>
                      <Text style={styles.previewMetricVal}>
                        {socialPreview.metrics.experiment_effectiveness != null
                          ? `${Math.round(socialPreview.metrics.experiment_effectiveness)}%`
                          : '—'}
                      </Text>
                      <Text style={styles.previewMetricLabel}>Effectiveness</Text>
                    </View>
                  </View>

                  {/* Conditionally visible shared fields */}
                  {socialPreview.metrics.current_level && (
                    <View style={styles.previewSharedRow}>
                      <Ionicons name="ribbon-outline" size={14} color={Colors.primary} />
                      <Text style={styles.previewSharedText}>
                        Shared Level: <Text style={{ fontWeight: '700' }}>{socialPreview.metrics.current_level}</Text>
                      </Text>
                    </View>
                  )}

                  {socialPreview.metrics.behavior_score != null && (
                    <View style={styles.previewSharedRow}>
                      <Ionicons name="analytics-outline" size={14} color={Colors.secondary} />
                      <Text style={styles.previewSharedText}>
                        Shared Score: <Text style={{ fontWeight: '700' }}>{socialPreview.metrics.behavior_score.toFixed(0)}</Text>
                      </Text>
                    </View>
                  )}

                  {/* Milestones preview */}
                  {socialPreview.milestones && socialPreview.milestones.length > 0 && (
                    <View style={styles.previewMilestones}>
                      <Text style={styles.previewMilestonesTitle}>Public Milestones</Text>
                      {socialPreview.milestones.map((m, i) => (
                        <Text key={i} style={styles.previewMilestoneItem}>
                          • {m}
                        </Text>
                      ))}
                    </View>
                  )}
                </View>
              ) : null}
            </View>

            {/* ── 5. Social & Friends Shortcut ── */}
            <TouchableOpacity
              style={styles.socialNavCard}
              onPress={() => router.push('/(tabs)/insights' as any)}
              activeOpacity={0.8}
            >
              <View style={styles.socialNavLeft}>
                <View style={[styles.cardIconBox, { backgroundColor: Colors.surfaceTintViolet }]}>
                  <Ionicons name="people" size={18} color={Colors.primary} />
                </View>
                <View>
                  <Text style={styles.socialNavTitle}>Peer Circles & Friends</Text>
                  <Text style={styles.socialNavSub}>Manage connections and view friends' public progress</Text>
                </View>
              </View>
              <Ionicons name="chevron-forward" size={18} color={Colors.textSubtle} />
            </TouchableOpacity>

            {/* ── 6. Account Controls & Centralized Logout ── */}
            <View style={styles.sectionCard}>
              <View style={styles.cardHeaderRow}>
                <View style={[styles.cardIconBox, { backgroundColor: '#FEE2E2' }]}>
                  <Ionicons name="settings-outline" size={16} color={Colors.accentCoral} />
                </View>
                <Text style={styles.cardTitle}>Account</Text>
              </View>

              <Text style={styles.sectionSubtitle}>
                Session tokens are persisted securely in on-device SecureStore.
              </Text>

              <TouchableOpacity
                style={styles.logoutButton}
                onPress={handleLogoutPress}
                disabled={isLoggingOut}
                activeOpacity={0.8}
              >
                {isLoggingOut ? (
                  <ActivityIndicator size="small" color="#DC2626" />
                ) : (
                  <>
                    <Ionicons name="log-out-outline" size={18} color="#DC2626" />
                    <View style={{ flex: 1 }}>
                      <Text style={styles.logoutBtnTitle}>Log Out</Text>
                      <Text style={styles.logoutBtnSub}>Sign out of this FocusLoop account</Text>
                    </View>
                    <Ionicons name="chevron-forward" size={16} color="#DC2626" />
                  </>
                )}
              </TouchableOpacity>
            </View>
          </>
        )}
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  topHeader: {
    height: 56,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(252, 248, 255, 0.95)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 0, 0, 0.04)',
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: Colors.textStrong,
  },
  container: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 40,
    gap: 16,
  },
  loadingBox: {
    padding: 40,
    alignItems: 'center',
    gap: 12,
  },
  loadingText: {
    fontSize: 13,
    color: Colors.textSubtle,
  },
  errorBox: {
    backgroundColor: '#FEE2E2',
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
    gap: 8,
  },
  errorTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#B91C1C',
  },
  errorDesc: {
    fontSize: 12,
    color: '#B91C1C',
    textAlign: 'center',
  },
  retryBtn: {
    marginTop: 8,
    backgroundColor: '#DC2626',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 12,
  },
  retryBtnText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  identityCard: {
    backgroundColor: Colors.neutralCard,
    borderRadius: 16,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  avatarLarge: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: Colors.primaryContainer,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarInitial: {
    fontSize: 24,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  identityTextColumn: {
    flex: 1,
    gap: 2,
  },
  profileName: {
    fontSize: 18,
    fontWeight: '700',
    color: Colors.textStrong,
  },
  profileHandle: {
    fontSize: 13,
    color: Colors.textSubtle,
  },
  profileEmail: {
    fontSize: 11,
    color: Colors.textMuted,
    marginTop: 2,
  },
  sectionCard: {
    backgroundColor: Colors.neutralCard,
    borderRadius: 16,
    padding: 16,
    shadowColor: '#64748B',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  cardHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  cardIconBox: {
    width: 30,
    height: 30,
    borderRadius: 8,
    backgroundColor: Colors.surfaceTintViolet,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: Colors.textStrong,
    flex: 1,
  },
  privateOwnerTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: Colors.surfaceTintMint,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
  },
  privateOwnerText: {
    fontSize: 10,
    fontWeight: '700',
    color: Colors.secondary,
  },
  publicTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: Colors.surfaceTintViolet,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
  },
  publicTagText: {
    fontSize: 10,
    fontWeight: '700',
    color: Colors.primary,
  },
  sectionSubtitle: {
    fontSize: 12,
    color: Colors.textSubtle,
    marginBottom: 14,
    lineHeight: 16,
  },
  metricsGrid: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 12,
  },
  metricTile: {
    flex: 1,
    borderRadius: 14,
    padding: 12,
    justifyContent: 'space-between',
    minHeight: 100,
  },
  metricTileHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  metricLabel: {
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  privacyMiniBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  privacyMiniText: {
    fontSize: 9,
    fontWeight: '600',
    color: Colors.textMuted,
  },
  metricValueLarge: {
    fontSize: 22,
    fontWeight: '700',
    color: Colors.textStrong,
    marginVertical: 4,
  },
  metricSub: {
    fontSize: 10,
    color: Colors.textSubtle,
  },
  publicMetricsStrip: {
    flexDirection: 'row',
    backgroundColor: Colors.surfaceContainerLowest,
    borderRadius: 12,
    padding: 12,
    alignItems: 'center',
    justifyContent: 'space-around',
    borderWidth: 1,
    borderColor: Colors.neutralBorder,
  },
  publicMetricCol: {
    alignItems: 'center',
    flex: 1,
  },
  publicMetricVal: {
    fontSize: 16,
    fontWeight: '700',
    color: Colors.textStrong,
  },
  publicMetricLabel: {
    fontSize: 10,
    color: Colors.textSubtle,
    marginTop: 2,
  },
  metricDivider: {
    width: 1,
    height: 24,
    backgroundColor: Colors.neutralBorder,
  },
  togglesList: {
    gap: 14,
  },
  toggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 4,
  },
  toggleInfo: {
    flex: 1,
    paddingRight: 12,
  },
  toggleTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  toggleTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: Colors.textStrong,
  },
  toggleDesc: {
    fontSize: 11,
    color: Colors.textSubtle,
    marginTop: 2,
    lineHeight: 15,
  },
  badgePill: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  badgePublic: {
    backgroundColor: Colors.surfaceTintMint,
  },
  badgePrivate: {
    backgroundColor: '#F3F4F6',
  },
  badgeText: {
    fontSize: 9,
    fontWeight: '700',
  },
  badgeTextPublic: {
    color: Colors.secondary,
  },
  badgeTextPrivate: {
    color: '#6B7280',
  },
  previewContainer: {
    backgroundColor: Colors.neutralCanvas,
    borderRadius: 14,
    padding: 14,
    gap: 10,
    borderWidth: 1,
    borderColor: Colors.neutralBorder,
  },
  previewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  previewAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.surfaceTintViolet,
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewAvatarText: {
    fontSize: 14,
    fontWeight: '700',
    color: Colors.primary,
  },
  previewName: {
    fontSize: 14,
    fontWeight: '700',
    color: Colors.textStrong,
  },
  previewSub: {
    fontSize: 11,
    color: Colors.textSubtle,
  },
  previewMetricsGrid: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 4,
  },
  previewMetricItem: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.neutralBorder,
  },
  previewMetricVal: {
    fontSize: 14,
    fontWeight: '700',
    color: Colors.secondary,
  },
  previewMetricLabel: {
    fontSize: 9,
    color: Colors.textSubtle,
    marginTop: 2,
  },
  previewSharedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#FFFFFF',
    padding: 8,
    borderRadius: 8,
  },
  previewSharedText: {
    fontSize: 11,
    color: Colors.textStrong,
  },
  previewMilestones: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 8,
    gap: 4,
  },
  previewMilestonesTitle: {
    fontSize: 10,
    fontWeight: '700',
    color: Colors.textSubtle,
    letterSpacing: 0.5,
  },
  previewMilestoneItem: {
    fontSize: 11,
    color: Colors.textStrong,
  },
  socialNavCard: {
    backgroundColor: Colors.neutralCard,
    borderRadius: 16,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  socialNavLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  socialNavTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: Colors.textStrong,
  },
  socialNavSub: {
    fontSize: 11,
    color: Colors.textSubtle,
    marginTop: 2,
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FECACA',
    borderRadius: 12,
    padding: 14,
    marginTop: 8,
  },
  logoutBtnTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#DC2626',
  },
  logoutBtnSub: {
    fontSize: 11,
    color: '#EF4444',
  },
  contextSummaryBox: {
    backgroundColor: '#F8FAFC',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 14,
    marginBottom: 14,
    gap: 12,
  },
  contextSummaryRow: {
    gap: 3,
  },
  contextLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: '#94A3B8',
    letterSpacing: 0.6,
  },
  contextValue: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1A1848',
    lineHeight: 18,
  },
  editContextBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#F5F3FF',
    borderWidth: 1,
    borderColor: '#DDD6FE',
    borderRadius: 12,
    paddingVertical: 12,
  },
  editContextBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: Colors.primary,
  },
});
